### ISSUE TITLE
不知什么原因，无法正常使用。

### ISSUE THREAD

**Issue by I-Info** [yqchilde/rebirth#1]
您好。首先必须说这个主题很好看。但是目前存在一些问题，无法正常使用。在本地服务器测试时，启用主题后，网站就显示500报错（iis）。另外，文章评论似乎不显示。之前的页面中内容消失，但也可能与我的配置有关。样式表中似乎存在一些问题，为什么样式表没有换行？虽然现在没法使用，但是急切希望我的网站能够用上这个主题。

**Comment by yqchilde** [comment]
IIS报错500我想是服务器配置问题，因为我用的是lnmp，对iis不太了解，没法帮到你。
该主题用的评论是[valine.js](https://valine.js.org/)，只需要按照官网申请leancloud账号就可以，免费版即可，所以不支持wordpress自带的评论，如果要使用该主题，建议关闭自带评论。
样式表是指哪里呢，如果可以请截个图。

**Comment by I-Info** [comment]
样式表指的是：style.css。为什么里面的代码没有换行呢？似乎中间有些错误。

**Comment by yqchilde** [comment]
style.css代码是压缩过的，可以用[css美化](https://tool.lu/css)，这里还原，此外样式如果有问题麻烦告知一下，还有其他问题请f12看是否有其他报错。

**Comment by I-Info** [comment]
哦，原来是这样，如果要编辑起来可能有点麻烦了。主要因为一些元素不能正常显示导致不能正常使用。有时间的话，我打算再在我的网站上测试一下。然后把具体问题反馈给你。

**Comment by I-Info** [comment]
下面是目前发现的一些bug：
=====
1.无论是新建还是原先的页面，下面的内容显示的是一片空白（标题可以显示，文章可以显示）。
2.默认文章图片不能加载：默认图片的资源*background-image: url('/wp-content/themes/rebirth')*，这个路径显然是不正确的。
3.导航下面空白。
4.图片显示诡异，没用进行缩放。如果图像过大，直接超出屏幕范围。
5.文章的一些wordpress元素消失，比如说按钮，分页符（导致文章第二页直接消失）。
*************
另外的一些问题：
**********
6.想知道您的博客的安装环境php版本，排除php版本问题。我使用的php版本为7.3
7.另外，想知道你的网站代码框/代码高亮是如何实现的？
8.关于页面如何修改？

**Comment by I-Info** [comment]
另外，希望在友链页面添加一个功能：链接可以按照分类目录进行分类。

**Comment by yqchilde** [comment]
首先最好是可以提供截图，github的issue也是支持图片的，只需要安装markdown格式即可，下面回答你的问题。
1.  新建页面代表模板页，在REAMDE.md里面提到过，模板页要安装wordpress的模板要求编写（或者参考我在主题page目录下的文件，是我的友链和关于页面模板），并且编写好了在新建页面里面选择即可，如下：
![image.png](https://i.loli.net/2020/03/28/mBadtC7vRU8ZPi2.png)
2. 默认文章图片是在后台设置的，具体看图片：
![image.png](https://i.loli.net/2020/03/28/ULjlTmDX9IS5MVs.png)
3. 导航空白是没有添加导航，添加也在后台主题设置，安装提示填写完整的json格式
4. 听起来是某些样式丢失，但是希望提供截图，或者我可以看到的，不然我也不确定什么情况
5. 同上
6. 我的php版本也是7.3
7. 代码高亮是`prism.js`，可以去官网了解一下
8. 关于页面，在主题的 `page` 目录下的 `page-about.php` 页面，这是外加的，可以自由编写的wordpress标准的页面模板
9. 友链的页面最近会单独做一个可以分类的页面上传

**Comment by I-Info** [comment]
消失的元素：
![image](https://user-images.githubusercontent.com/49438478/77819695-b7cbe180-7117-11ea-9a5f-9346f5440172.png)
![批注 2020-03-28 170924](https://user-images.githubusercontent.com/49438478/77819706-d500b000-7117-11ea-9de6-95dfc2000d4d.png)
****
页面问题：
![image](https://user-images.githubusercontent.com/49438478/77819761-55271580-7118-11ea-8e1a-f1bc4529b9dd.png)
![image](https://user-images.githubusercontent.com/49438478/77819791-9f0ffb80-7118-11ea-81c7-bc6df8e6e2cf.png)
个人猜测：可能是页面的默认模板存在问题，用其他的模板（友链、关于）页面可以正常显示。
*****
导航莫名奇妙又可以显示了。
默认图片的默认值有问题吧。我如果不修改，就无法正确显示主题image的默认图片。手动修改完路径后可以使用。
****
样式错误的图片：
![批注 2020-03-28 170923](https://user-images.githubusercontent.com/49438478/77819855-0fb71800-7119-11ea-9f79-d1f986981943.png)
![image](https://user-images.githubusercontent.com/49438478/77819980-f2cf1480-7119-11ea-96db-2ca0dbe13a1f.png)
****
以上就是问题的反馈信息了。

**Comment by I-Info** [comment]
![image](https://user-images.githubusercontent.com/49438478/77820521-e51b8e00-711d-11ea-8065-b3813fc68d80.png)
如图。

**Comment by yqchilde** [comment]
好的，问题知道了，差不多已经知道你的所有问题答案了。
1. 你用的是markdown语法吧，但是wordpress默认的文章编辑器是不支持markdown的，目前也没有处理默认的（抱歉，后续可能有），关于wordpress的编辑器插件，推荐使用`wp-githuber`，这也是我一直在用的，确实是没有想到默认编辑器的问题，很抱歉。
2. 新建页面最好是在`page`目录再添加一个页面，命名如下 `page-xxx.php`，然后要注意注释内容，这个地方很关键，是后台识别的关键。其实就是一个php文件，规定了名字，规定了注释内容，其他内容都是html内容。
3. 修改完有时候不显示可能是浏览器缓存，可以`ctrl+f5`强制刷新
4. 图片问题太大，就是你的文章内容里面的图片，最好是以正常格式的（例如jpg,png,webp等格式），`.php`结尾的文件不可以的
5. 分类图片的设置，在主题设置里面有个分类图片设置区域，严格按照我提示内容的json格式写就可以，tag_ID获取方法如下
![image.png](https://i.loli.net/2020/03/28/83hXRbALpPJoE9Z.png)
![image.png](https://i.loli.net/2020/03/28/kR6srxdUPtwXqCS.png)

**Comment by yqchilde** [comment]
文章解析是严格按照markdown语法转的html，所以目前需要按照markdown写法写文章

**Comment by I-Info** [comment]
就是说，目前不能用默认的wordpress编辑器。所以其中的一些元素（分页符、按钮之类的wp编辑器中的元素）也是不能使用的吧。所以说我目前需要使用markdown的编辑器，这我也是可以接受的。
关于上面的第二点，我不是很清楚具体改怎么做，是需要新建一个模板吗。

**Comment by yqchilde** [comment]
是的，在page目录里面创建一个`page-xxx.php` 的文件，然后里面是你自定义页面的样子，写html代码就行，在那个目录下有`page-about.php` , `page-links` 这两个文件，分别是关于和友链的单页，你可以参考一下

**Comment by I-Info** [comment]
这个我明白，但是能否实现：当我选择默认模板时，就可以解析我在编辑器中的编写的内容呢？

**Comment by I-Info** [comment]
因为，比如说每次修改“xxx”页面，我都得修改“page-xxx.php”文件。这显然是比较麻烦的事情，希望以后能够优化。

**Comment by I-Info** [comment]
谢谢您的帮助，目前已经解决了大部分的问题了。

**Comment by yqchilde** [comment]
当我选择默认模板时，就可以解析我在编辑器中的编写的内容呢？
我想应该是可以的，可以查看一下相关文档（这个就属于wp相关了，和主题没有关系），关于这个创建页面，平时用的地方并不多，因为主要是写博文，一切其他的页面，本来就是自己添加的，只不过一般主体设计都会带几个页面模板，这并不意味着让你自己经常写独立页面，毕竟需要的独立页面也就那几个，其他都是文章页面即wordpress内置页面。

**Comment by I-Info** [comment]
另外，我还发现：之前显示过大的图片（.php），当我用markdown编辑器修改后，也可以正常显示了
看来主要的还是编辑器的问题

**Comment by yqchilde** [comment]
是的，因为目前主题解析的是markdown转换之后的html代码，所以按照原来的是部分解析错误的

**Comment by I-Info** [comment]
嗯，你说的对。多亏了您的帮助，现在我已经成功的用上了这个主题。😊

**Comment by I-Info** [comment]
后续有问题我还会继续反馈的。谢谢！
