### ISSUE TITLE
请问valine设置中的serverURLs怎么填写？

### ISSUE THREAD

**Issue by I-Info** [yqchilde/rebirth#10]
如题，不太理解，难道是leancloud中的api访问域名，目前我是空着的？
另外我的网站valine评论系统报错：
----
Code -1: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc. [N/A GET https://us.avoscloud.com/1.1/classes/Comment]
----

**Comment by yqchilde** [comment]
> ## 如题，不太理解，难道是leancloud中的api访问域名，目前我是空着的？
> 另外我的网站valine评论系统报错：
> ## Code -1: Request has been terminated
> Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc. [N/A GET https://us.avoscloud.com/1.1/classes/Comment]

Leancloud后台绑定API域名，填写的就是这个域名
![image](https://user-images.githubusercontent.com/36953759/82106180-00843c00-9752-11ea-8747-83b3a9bd757f.png)
![image](https://user-images.githubusercontent.com/36953759/82106191-10038500-9752-11ea-9507-4e6262caf4f5.png)

**Comment by yqchilde** [comment]
具体配置看Valine给出的配置就可以
[https://valine.js.org/quickstart.html](https://valine.js.org/quickstart.html)

**Comment by I-Info** [comment]
谢谢您的解答，可是请问报错怎么办呢？

**Comment by yqchilde** [comment]
> 谢谢您的解答，可是请问报错怎么办呢？

我想应该是没有写正确的api导致的，如果暂时不需要评论系统
打开主题根目录/tpl/single/single-content.php，注释掉317-319行代码

**Comment by I-Info** [comment]
> > 谢谢您的解答，可是请问报错怎么办呢？
> 
> 我想应该是没有写正确的api导致的，如果暂时不需要评论系统
> 打开主题根目录/tpl/single/single-content.php，注释掉317-319行代码

哎呀，现在又恢复了，不知道是不是和leancloud的休眠有关。谢谢：）
