### ISSUE TITLE
关于文章分类

### ISSUE THREAD

**Issue by ybquality** [yqchilde/rebirth#11]
请问作者你那个文章分类目录和页面是怎么绑定在一起的。我在菜单设置的页面就不会有文章，如果菜单设置的分类目录就会提示没有这个文件

**Comment by ybquality** [comment]
就是您那个网站每个文章是发布在不同的分类目录里面的，但是怎么通过菜单里的导航栏进入那个分类目录，我如果直接在菜单里添加分类目录是没有页面的。我的猜想应该是将分类目录和页面绑定起来，但是不知道该如何实现，还希望作者进行详细的解答。

**Comment by yqchilde** [comment]
> 就是您那个网站每个文章是发布在不同的分类目录里面的，但是怎么通过菜单里的导航栏进入那个分类目录，我如果直接在菜单里添加分类目录是没有页面的。我的猜想应该是将分类目录和页面绑定起来，但是不知道该如何实现，还希望作者进行详细的解答。

Wordpress在发布文章时候可以选择目录的，只要提前添加好目录（文章->分类目录），在发布文章的时候选择就可以
![image](https://user-images.githubusercontent.com/36953759/82725305-b16c7700-9d0e-11ea-9b64-637e1b0e3148.png)
![image](https://user-images.githubusercontent.com/36953759/82725328-d19c3600-9d0e-11ea-87db-6e4f106b7190.png)

这是我的菜单的设置
![image](https://user-images.githubusercontent.com/36953759/82725353-f2fd2200-9d0e-11ea-8506-582565939468.png)

**Comment by ybquality** [comment]
可能是那个固定链接的问题，我没有办法访问分类目录

**Comment by ybquality** [comment]
还有这个分类目录的背景图设置，好像没有办法加载欸，推荐博主下个版本都弄一些示范。
![TIM截图20200523205036](https://user-images.githubusercontent.com/65755259/82731102-120faa00-9d37-11ea-90de-6428fb3ad984.png)

**Comment by yqchilde** [comment]
> 可能是那个固定链接的问题，我没有办法访问分类目录

这和固定链接没有关系，说实话现在没有很清楚的知道你想做什么，如果可以，请留下测试站，或者截图说下你出现的问题。

**Comment by yqchilde** [comment]
在README.md里面我写过实例，
https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95

动力钦钦 <notifications@github.com> 于2020年5月23日周六 下午8:51写道：
