### ISSUE TITLE
关于Valine.js第三方评论

### ISSUE THREAD

**Issue by orange886** [yqchilde/rebirth#12]
请问第三方评论怎么配置？
Valine->serverURLs
这个在哪里能找到配置信息？

**Comment by yqchilde** [comment]
> 请问第三方评论怎么配置？
> Valine->serverURLs
> 这个在哪里能找到配置信息？

我在这里提到了
[https://github.com/yqchilde/rebirth/issues/10](https://github.com/yqchilde/rebirth/issues/10)

**Comment by fangcaicheng** [comment]
> > 请问
第三方评论怎么配置？
> > Valine->serverURLs
> > 这个在哪里能找到配置信息？
> 
> 我在这里提到了
> #10

**Comment by orange886** [comment]
> > 瓦林-gt;服务器 URL  ？
> 
> 
> #10

我添加了域名，也域名添加进去了，还是没有生效。

**Comment by yqchilde** [comment]
> > > 瓦林-gt;服务器 URL  ？
> > 
> > 
> > #10
> 
> 我添加了域名，也域名添加进去了，还是没有生效。

请在Leancloud后台配置好信息确定域名生效可以用

**Comment by orange886** [comment]
> > > > 瓦林-gt;服务器 URL  ？
> > > 
> > > 
> > > #10
> > 
> > 
> > 我添加了域名，也域名添加进去了，还是没有生效。
> 
> 请在Leancloud后台配置好信息确定域名生效可以用

安全域名也添加了呀，还需要配置哪些信息，求解！

**Comment by yqchilde** [comment]
不是安全域名，是绑定的api域名，如果可以，请截个图我看一下是否成功

**Comment by fangcaicheng** [comment]
> 不是安全域名，是绑定的api域名，如果可以，请截个图我看一下是否成功
是的api已经绑定成功了的，而且绑定的api域名也填到了serverURLs配置了，域名也开启ssl

**Comment by orange886** [comment]
> 不是安全域名，是绑定的api域名，如果可以，请截个图我看一下是否成功

是的api已经绑定成功了的，而且绑定的api域名也填到了serverURLs配置了，域名也开启ssl

**Comment by yqchilde** [comment]
name

> > 不是安全域名，是绑定的api域名，如果可以，请截个图我看一下是否成功
> 
> 是的api已经绑定成功了的，而且绑定的api域名也填到了serverURLs配置了，域名也开启ssl

那么只需要在主题里设置，相关的id和key就可以了，设置好了之后，打开网站看看评论框底下提示什么错误，如果有错误会直接报错错误代码

**Comment by orange886** [comment]
> name
> 
> > > 不是安全域名，是绑定的api域名，如果可以，请截个图我看一下是否成功
> > 
> > 
> > 是的api已经绑定成功了的，而且绑定的api域名也填到了serverURLs配置了，域名也开启ssl
> 
> 那么只需要在主题里设置，相关的id和key就可以了，设置好了之后，打开网站看看评论框底下提示什么错误，如果有错误会直接报错错误代码


Warning
: Invalid argument supplied for foreach() in
/www/wwwroot/orange.qqccy.cn/wp-content/themes/rebirth/tpl/single/single-content.php

**Comment by yqchilde** [comment]
浏览了你的网站，评论是好的，没有问题，报错的位置不是评论，是信息展示区，这块的bug明晚修修吧，白天要上班没有时间了，只能明天晚上回来了

**Comment by orange886** [comment]
> 浏览了你的网站，评论是好的，没有问题，报错的位置不是评论，是信息展示区，这块的bug明晚修修吧，白天要上班没有时间了，只能明天晚上回来了

那现在怎么修复呢

**Comment by orange886** [comment]
> 浏览了你的网站，评论是好的，没有问题，报错的位置不是评论，是信息展示区，这块的bug明晚修修吧，白天要上班没有时间了，只能明天晚上回来了

能否把你联系方式我加一下，请教如何修复这个问题

**Comment by yqchilde** [comment]
暂时的方法是填写分类图片，因为默认分类图片没有就是显示错误，填写规则看这里
[https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95](https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95)

晚上会结局掉这个默认没有图片的bug

**Comment by orange886** [comment]
> 暂时的方法是填写分类图片，因为默认分类图片没有就是显示错误，填写规则看这里
> https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95
> 
> 晚上会结局掉这个默认没有图片的bug

请问修复好了吗？还有个问题，为什么作者信息的头像换不成功？

**Comment by yqchilde** [comment]
已修复，合并最新代码即可。[https://github.com/yqchilde/rebirth/commit/40dcfc88e79c578ae63dd565577764944d9849ea](https://github.com/yqchilde/rebirth/commit/40dcfc88e79c578ae63dd565577764944d9849ea)

有问题提交截图，为了更快为你解答，没有图片，很难知道问题

要上班，开源项目抽空更新，勿催，谢谢

**Comment by orange886** [comment]
> 已修复，合并最新代码即可。[40dcfc8](https://github.com/yqchilde/rebirth/commit/40dcfc88e79c578ae63dd565577764944d9849ea)
> 
> 有问题提交截图，为了更快为你解答，没有图片，很难知道问题
> 
> 要上班，开源项目抽空更新，勿催，谢谢

谢谢您的贡献
这里已经把文章底部修复好了，但是分类页的图片还是没有显示出。这里报错。

- [ 报错](https://orange.qqccy.cn/wp-content/uploads/2020/06/报错.png)

**Comment by yqchilde** [comment]
这个是没有设置菜单的问题，设置了菜单就不会出现了

**Comment by orange886** [comment]
> 这个是没有设置菜单的问题，设置了菜单就不会出现了

谢谢！非常感谢，还有个问题，分类的图片没有出来，是我配置的问题吗？还是？

- [ 审查元素] (https://orange.qqccy.cn/wp-content/uploads/2020/06/报错.png)

- [ 后台配置] (https://orange.qqccy.cn/wp-content/uploads/2020/06/后台配置.png)

**Comment by yqchilde** [comment]
已修复当没有设置菜单时的报错，但是还是希望设置菜单
[https://github.com/yqchilde/rebirth/commit/52ec00d0c415c4a73254f7b42d8a1b0db6c94282](https://github.com/yqchilde/rebirth/commit/52ec00d0c415c4a73254f7b42d8a1b0db6c94282)

分类的设置请看这里，[https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95](https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95)

**Comment by orange886** [comment]
> 已修复当没有设置菜单时的报错，但是还是希望设置菜单
> [52ec00d](https://github.com/yqchilde/rebirth/commit/52ec00d0c415c4a73254f7b42d8a1b0db6c94282)
> 
> 分类的设置请看这里，https://github.com/yqchilde/rebirth#tag_id%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95

是的，分类的设置已经按照教程里的来设置了，但是图片依然没出来！上面截图上有后台设置的内容。

**Comment by yqchilde** [comment]
分类ID确定是1,2,3吗？记得ID要对应

**Comment by orange886** [comment]
> 分类ID确定是1,2,3吗？记得ID要对应

是的，确认没错，

- [id] (https://orange.qqccy.cn/wp-content/uploads/2020/06/2.png)
(https://orange.qqccy.cn/wp-content/uploads/2020/06/3.png)
(https://orange.qqccy.cn/wp-content/uploads/2020/06/id.png)

**Comment by yqchilde** [comment]
又看了一次，你这个没有按照json的格式来啊，有三个点，你自己看下，写好之后放在[https://www.sojson.com/](https://www.sojson.com/)里面解析看看是不是json
[https://orange.qqccy.cn/wp-content/uploads/2020/06/%E5%90%8E%E5%8F%B0%E9%85%8D%E7%BD%AE.png](https://orange.qqccy.cn/wp-content/uploads/2020/06/%E5%90%8E%E5%8F%B0%E9%85%8D%E7%BD%AE.png)

**Comment by orange886** [comment]
> 又看了一次，你这个没有按照json的格式来啊，有三个点，你自己看下，写好之后放在https://www.sojson.com/里面解析看看是不是json
> https://orange.qqccy.cn/wp-content/uploads/2020/06/%E5%90%8E%E5%8F%B0%E9%85%8D%E7%BD%AE.png

去掉后面三个点，还是没有显示出来，放到json解析，就是这个格式。

- [6] (https://orange.qqccy.cn/wp-content/uploads/2020/06/6.png)

- [5 ] (https://orange.qqccy.cn/wp-content/uploads/2020/06/5.png)

**Comment by yqchilde** [comment]
...json的最后一条对象后面没有逗号，给你网站不是放进去，是要点解析，显示解析成功才行

**Comment by orange886** [comment]
> 给你网站不是放进去，是

谢谢，感谢你的回复，在遇到问题，我在来提。谢谢！

**Comment by yqchilde** [comment]
ok
