### ISSUE TITLE
渲染受阻

### ISSUE THREAD

**Issue by NGXTDN** [yqchilde/rebirth#13]
https://hm.baidu.com/hm.js?9327590ef57d577af3cebe5a982d84b4
具体链接在这里！在控制台里一直标红！

**Comment by yqchilde** [comment]
> https://hm.baidu.com/hm.js?9327590ef57d577af3cebe5a982d84b4
> 具体链接在这里！在控制台里一直标红！

请问是本地环境吗，可以提供一下截图吗，我好确定问题所在。

**Comment by NGXTDN** [comment]
https://i.loli.net/2020/08/07/L9ONio6AHlBEVRD.png
