### ISSUE TITLE
关于评论的一个bug

### ISSUE THREAD

**Issue by I-Info** [yqchilde/rebirth#2]
我发现了一个小问题（不知道该不该在这里问）：
用一个浏览器在文章下面评论时，短时间可以连续发评论。但是刷新页面后，回复的按钮就失效了（按下去没反应），即不能再发评论了。
****
当我使用另外一个浏览器时，评论又可以正常使用了。
试着清除原来浏览器的缓存，评论恢复正常。
还原问题后，再试着清除cookie后，评论也恢复了正常。
****
因此猜测问题的原因和cookie有关。请问有什么解决办法吗？

**Comment by yqchilde** [comment]
你这个问题，我没有出现过，试了下复现问题，也没有出现，而且Valine.js三方评论系统是直接引用官方写法，不存在主题控制cookie，或许你可以在我blog里面进行评论测试

**Comment by I-Info** [comment]
目前猜测是我的网站的本地存储出现了问题。应该与主题无关。我准备去valine发issue问一下这个问题。
