### ISSUE TITLE
一个css的小问题。

### ISSUE THREAD

**Issue by I-Info** [yqchilde/rebirth#3]
又来提交bug了。希望不要责怪我事情多😂
下面是正文：
***
![image](https://user-images.githubusercontent.com/49438478/77918674-cc9ea580-72ce-11ea-9b2e-e5def99e62f5.png)
如图，当开启夜间模式时，这个阴影遮罩似乎有一点问题。
缩小页面就更加明显了。
![image](https://user-images.githubusercontent.com/49438478/77919394-b5ac8300-72cf-11ea-8e98-0e129165777e.png)

为什么头像被挤压了呢？
***
就是这样一个问题，感谢您的热心解答！

**Comment by yqchilde** [comment]
已修复，请更新最新的两个提交文件

**Comment by I-Info** [comment]
求教，有没有好的办法使得主题的文件和git存储库同步更新呢？

**Comment by yqchilde** [comment]
学习使用git命令，`git pull`

**Comment by I-Info** [comment]
好的，谢谢。问题已解决！
