### ISSUE TITLE
为什么不能搜索

### ISSUE THREAD

**Issue by telidux** [yqchilde/rebirth#4]
作者你好，你的主题非常好，唯一的问题就是搜索好像不能用，是我操作有问题吗？

**Comment by yqchilde** [comment]
如果可以，请告诉我是在本地搭建的环境还是已经线上，如果线上，方便的话，可以告知网址吗，我帮你看看。
如果不方便，可以在F12，然后看看是不是有trick.js文件没有加载到，我的bolg是可以搜索的，也可以访问我的查看。

**Comment by I-Info** [comment]
表示，我的博客也是可以搜索的。。😂 @telidux

**Comment by telidux** [comment]
> 如果可以，请告诉我是在本地建造的环境还是已经线上，如果线上，方便的话，可以告知网址吗，我帮你看看。
> 如果不方便，可以在F12，然后看看是不是有trick .js文件没有加载到，我的bolg是可以搜索的，也可以访问我的查看。

trick .js文件确实没有被加载

**Comment by telidux** [comment]
> 如果可以，请告诉我是在本地建造的环境还是已经线上，如果线上，方便的话，可以告知网址吗，我帮你看看。
> 如果不方便，可以在F12，然后看看是不是有trick .js文件没有加载到，我的bolg是可以搜索的，也可以访问我的查看。
我目前是本地环境，我的网站还没备案

**Comment by yqchilde** [comment]
有挪动主题源代码文件目录么，可以看一下报错是404，还是什么问题，可以在这里贴一个图

**Comment by telidux** [comment]
> 有挪动主题源代码文件目录么，可以看一下报错是404，还是什么问题，可以在这里贴一个图

没有404也没有移动主题源代码目录

**Comment by yqchilde** [comment]
> > 有挪动主题源代码文件目录么，可以看一下报错是404，还是什么问题，可以在这里贴一个图
> 
> 没有404也没有移动主题源代码目录

麻烦告知一下请求具体错误，就是贴一下请求信息

**Comment by telidux** [comment]
我知道了因该是我的wordpress出错了，谢谢了

**Comment by yqchilde** [comment]
> 我知道了因该是我的wordpress出错了，谢谢了

好的，谢谢使用
