### ISSUE TITLE
上传后发现问题

### ISSUE THREAD

**Issue by telidux** [yqchilde/rebirth#5]
作者你好，上次在本地调试成功了，但是上传后再次发现问题，搜索再次不可用，另外云标签点击后出现404，附上在线链接http://tblog.enbar.cn/

**Comment by yqchilde** [comment]
> 作者你好，上次在本地调试成功了，但是上传后再次发现问题，搜索再次不可用，另外云标签点击后出现404，附上在线链接http://tblog.enbar.cn/

标签是在后台设置的
![image](https://user-images.githubusercontent.com/36953759/79061556-f2ab4900-7cc3-11ea-8f2e-3ec2cb8267c3.png)

**Comment by telidux** [comment]
那么请问搜索时什么原因

**Comment by yqchilde** [comment]
> 那么请问搜索时什么原因

我一下也没找到解决方法，你再试着发一篇文章看看
![image](https://user-images.githubusercontent.com/36953759/79063164-871ca800-7cd2-11ea-9c66-5de70977e5fe.png)

**Comment by telidux** [comment]
我提供一个测试的管理员吧
不然你调试起来不方便
用户名：yqchilde
密 码：test1234

**Comment by yqchilde** [comment]
> 我提供一个测试的管理员吧
> 不然你调试起来不方便
> 用户名：yqchilde
> 密 码：test1234

你好，可以加我q吗，还有一些资料，方便的话我q1455723643
