### ISSUE TITLE
页面出现Invalid argument supplied for foreach() in 错误

### ISSUE THREAD

**Issue by wanghaihua** [yqchilde/rebirth#9]
Warning
: Invalid argument supplied for foreach() in 
/www/wwwroot/xxx/wp-content/themes/rebirth/tpl/single/single-content.php

标签栏也有类似错误
加上（array）不报错，但是排版好似乱了？

**Comment by yqchilde** [comment]
> Warning
> : Invalid argument supplied for foreach() in
> /www/wwwroot/xxx/wp-content/themes/rebirth/tpl/single/single-content.php
> 
> 标签栏也有类似错误
> 加上（array）不报错，但是排版好似乱了？

请留下网址或者贴一下图片，我看一下。
